services:
  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jobapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jobapp" ]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis-container
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./server/internal/platform/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    restart: unless-stopped

  grafana:
    container_name: grafana-container
    image: grafana/grafana:11.5.1
    ports:
      - "3030:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  prometheus_data:
  grafana_data:
